"""add foreignkey and relationship btw activities and user

Revision ID: 168f0775dd2f
Revises: 1a565942070d
Create Date: 2023-12-13 09:54:11.152905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168f0775dd2f'
down_revision = '1a565942070d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('seasonal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('seasonal')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
