"""validation method to validate season modified for the column name

Revision ID: 1968b1d67c1a
Revises: 168f0775dd2f
Create Date: 2023-12-13 09:57:11.058489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1968b1d67c1a'
down_revision = '168f0775dd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.String(), nullable=True))
        batch_op.drop_column('seasonal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seasonal', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('season')

    # ### end Alembic commands ###
